### ISSUE TITLE
Feature: User can view upcoming events and purchase tickets without logging in

### ISSUE THREAD

**Issue by marshall-vogt** [marshall-vogt/gemineye-productions-project#1]
## ⚙️ Feature

User will be able to view a list of upcoming events, including details about the event. User can purchase tickets or RSVP to events.

## 📐 Functionality

User can view upcoming events on the homepage and also have the option of a dedicated page to events. Each event will have the option to purchase tickets and will prompt user to either sign-in, create account, or checkout as a guest.

## 🖼️ Wireframes
<img width="820" alt="Screenshot 2023-10-01 at 7 32 53 PM" src="https://github.com/marshall-vogt/gemineye-productions-project/assets/131848819/f2dbe518-17dc-4c56-9e65-ecb261081601">

<img width="816" alt="Screenshot 2023-10-01 at 7 41 19 PM" src="https://github.com/marshall-vogt/gemineye-productions-project/assets/131848819/742dba05-06b2-4253-9c5c-260988ef1575">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include 'dummy' events for user to view.

### ☁️ Server Tasks

- [x] Update `server.ts` to make GET request from database to load all upcoming events.
- [x] Update 'server.ts' to make GET request to load details for a selected event.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a HomePage component to display image carousel and upcoming events.
- [x] Create a dedicated EventPage component to view events.
- [x] Create an EventDetails component to view event details and display event flyer.
- [x] Update EventDetails component to handle ticket purchasing.
- [x] Create a NavBar component to display logo and navigation buttons.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
